### PR TITLE
Improves performance of room assignments with additional subqueryloads

### PR DESCRIPTION
**Pull request by RobRuana**
🤞

### CODE REVIEW

**Comment by RobRuana** [comment]
The diff looks weird, but it's mostly reformatting. The functional difference is the calls to `subqueryload()`

**Comment by earl7399** [comment]
+1
(note: whoever wrote old line #319 needs a talking to - preferably from Red of That 70's Show)

**Comment by EliAndrewC** [comment]
+1

> (note: whoever wrote old line #319 needs a talking to - preferably from Red of That 70's Show)

Haha, it was probably me, though honestly I have no idea why I wouldn't have broken that line up like all the others.

My best guess is that I was like, "bleh, lemme just get this working and then I'll format it nicely later" and then later never came.  I have noticed that one of the nice things about doing code reviews is that by forcing me to review my own changes before they go live I manage to catch a lot of stuff like that before anyone else even has a chance to look at it!

So really the ACTUAL monster here is all the people who weren't helping me out at the time by reviewing my code :P  That's my excuse and I'm sticking to it!

**Comment by earl7399** [comment]
buncha jerks!

**Pull request merged**
